name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Zig
        run: |
          sudo apt update
          sudo apt search zig

      - name: Installed rust target
        run: |
          rustup target list --installed
