name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
          TZ: "Asia/Tokyo"
        run: |
          gh release create `date +'%Y-%m-%dT%H:%M:%S'` --generate-notes --target main
      
