name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
          TZ: "Asia/Tokyo"
        run: |
          last_tag=`git describe --tags --match="*-${{ github.ref_name }}" HEAD 2>/dev/null || true`
          new_tag=`date +'%Y-%m-%dT%H-%M-%S'`-${{ github.ref_name }}
          gh release create ${new_tag} --generate-notes --target ${{ github.ref_name }} --notes-start-tag "${last_tag}"
      
