name: Reusable

on:
  workflow_call:
    inputs:
      greeting:
        required: true
        type: string
        
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo ${{ inputs.greeting }}
          
